# Generated by Django 3.2 on 2021-05-19 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='phrasescore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
