# Generated by Django 3.2 on 2021-05-19 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_lesson_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='phrasescore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 18, 52, 953678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 18, 52, 895832, tzinfo=utc)),
        ),
    ]
