# Generated by Django 3.2 on 2021-05-19 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210520_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 19, 15, 299978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='phrasescore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 19, 15, 359819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='last_practiced',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 19, 15, 359819, tzinfo=utc)),
        ),
    ]
