# Generated by Django 3.2 on 2021-05-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210520_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phrasescore',
            name='last_practiced',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wordscore',
            name='last_practiced',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
