# Generated by Django 3.2 on 2021-05-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210520_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrasetranslation',
            name='node',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='node',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
